export interface JoaquinSentence {
  id: number;
  label: string;
}

export const allJoaquinSentences: JoaquinSentence[] = [
  "Amo arriba loh tio",
  "Feijoo asi en general",
  "un Politico random al que solo conoce joaquin",
  "er Beti (sin venir a cuento)",
  "el PP (sin venir a cuento)",
  "Fekir (sin venir a cuento)",
  "Somosaguas y somosvinos",
  "Moooostoles/El duque de mostoles",
  "ah yo pense que si, yoPenseQueSi",
  "Alvise perez",
  "el PP no va a pactar con vox",
  "Alberto cordoba",
  "Nivea",
  "Que buena esta Ayuso",
  "Puigdemont en un maletero",
  "Llamo a mi sicario que te pegue",
  "Joaquin Ordoñez le pego al rey juan carlos",
  "El Joaqui fue futbolista profesional",
  "ahi paraba mi Brañas",
  "el betis va a ganar la champions de aqui a 2070 (que me lo ha dicho ChatGPT)",
  "este año gana el betis",
  "Si mi abuela tuviera ruedas seria una bicicleta",
  "La cruzcampo es la mejor cerveza del mundo",
  "El betis es el mejor equipo del mundo",
  "cuando yo sea presidente del Betis...",
  "Te acuerdas cuando Mojica me dio la sudadera y David López los pantalones en el Rayo vs Mallorca?",
  "Hubo un tio que se fue andando desde Barakaldo a Madrid",
  "Alvaro valles",
  "No te voy a perdonar el dia que me pusiste con Maria la vieja",
  "Jaajaaaja a a a a a a (risa de subnormal)",
  "la lobete",
  "Soy como Kike Setien",
  "Mi rayito macho",
  "Ahi se subian Javier Bueriberi y Alejandro Fabricio",
  "La camiseta del Hercules",
  "pantalones con publicidad en el culo",
  "Tengo las mismas canas que pedro sanchez y mazon",
  "Parece esto un velatorio",
  "En la vida en la viiida, como diria esperanza aguirre",
  "El PP es el mejor partido de la historia de españa",
  "Estoy en contra de la explotacion de la mujer",
  "A ver si me van a violar",
  "Que tengo un sinus pilonidal",
  "Tu y yo somos como Revilla y Adrian Barbon",
  "No me extraña que los vascos voten a Bildu",
  "A mi me quieren hasta los catalanes",
  "[Nombre]-íííín, que tiene sueñíín"
].map((label, index) => ({ id: index + 1, label }));
