name: axe Linter

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  axe-linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Run axe Linter
        uses: dequelabs/axe-linter-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          api_key: ${{ secrets.DEQUE_API_KEY }}
